#config

## => Site Settings
title: DessaDot
email: freeoh100@gmail.com
url: https://dessadot.github.io
github_username: dessadot

highlighter: rouge
svg:
  optimize: true
# Build settings
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/

## => Language and Timezone
##############################
lang: ko
timezone: Asia/Seoul

## => Author and Social
##############################
author:
  type      : person
  name      : DessaDot
  bio       : 
  email     :
  googleplus: 
  medium    : 
  linkedin  : 
  github    : dessadot
  
