#config

## => Site Settings
title: DessaDot
email: freeoh100@gmail.com
url: https://dessadot.github.io
baseurl:
description: > Description
github_username: dessadot

highlighter: rouge
svg:
  optimize: true
# Build settings
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/

## => Language and Timezone
##############################
lang: ko
timezone: Asia/Seoul

## => Author and Social
##############################
author:
  type      : person
  name      : jETA
  url       : https://jetalog.net
  avatar    : 
  bio       : 
  email     :
  facebook  : 
  twitter   : 
  weibo     : 
  googleplus: 
  telegram  : 
  medium    : 
  zhihu     : 
  douban    : 
  linkedin  : 
  github    : dessadot
  npm       : dessadot
  
